[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"
ZELLIJ_SESSION_NAME = "$ZELLIJ_SESSION_NAME"
HELLO = "$HOME"

[font]
# linux laptop
# size = 9.5

# macos
size = 16

[font.offset]
x = 0

# linux laptop
# y = 0

# macos
y = 4

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Regular"


# https://stackoverflow.com/a/42461580
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mods = "Control"

[[keyboard.bindings]]
key = "P"
mods = "Command"
chars = "\u0001\u0070"

[[keyboard.bindings]]
key = "P"
mods = "Command|Shift"
chars = "\u0001\u0050"

[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u0001\u0008"

[[keyboard.bindings]]
key = "H"
mods = "Command|Alt"
chars = "\u0001\u0068"

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u0001\u000a"

[[keyboard.bindings]]
key = "J"
mods = "Command|Alt"
chars = "\u0001\u006a"

[[keyboard.bindings]]
key = "J"
mods = "Command|Shift"
chars = "\u0001\u004a"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u0001\u000b"

[[keyboard.bindings]]
key = "K"
mods = "Command|Alt"
chars = "\u0001\u006b"

[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
chars = "\u0001\u004b"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u0001\u000c"

[[keyboard.bindings]]
key = "L"
mods = "Command|Alt"
chars = "\u0001\u006c"
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0001\u0014"

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u0001\u0031"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u0001\u0032"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u0001\u0033"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u0001\u0034"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u0001\u0035"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u0001\u0036"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u0001\u0037"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u0001\u0038"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u0001\u0039"

[[keyboard.bindings]]
key = "A"
mods = "Command"
chars = "\u0001\u0001"

[[keyboard.bindings]]
key = "T"
mods = "Command|Shift"
chars = "\u0001\u0074"


[scrolling]
history = 100000

[window]
decorations = "Buttonless"
opacity = 0.9
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"
blur = true

# macos
# [window.padding]
# x = 93

[shell]
program = "/opt/homebrew/bin/tmux"
