[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
# linux laptop
# size = 9.5

# macos
size = 16

[font.offset]
x = 0

# linux laptop
# y = 0

# macos
y = 4

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Regular"

# https://stackoverflow.com/a/42461580
[keyboard]
bindings = [
  { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
  { chars = "\u001B[13;5u", key = "Return", mods = "Control" },
  { action = "Paste", key = "V", mods = "Super" },
  { action = "Copy", key = "C", mods = "Super" },
  # tab
  { key = "T", mods = "Command", chars = "\u001b[14~\u006e" },
  { key = "P", mods = "Command", chars = "\u001b[13~\u006e" },
  { key = "1", mods = "Command", chars = "\u001b[14~\u0031" },
  { key = "2", mods = "Command", chars = "\u001b[14~\u0032" },
  { key = "3", mods = "Command", chars = "\u001b[14~\u0033" },
  { key = "4", mods = "Command", chars = "\u001b[14~\u0034" },
  { key = "5", mods = "Command", chars = "\u001b[14~\u0035" },
  { key = "6", mods = "Command", chars = "\u001b[14~\u0036" },
  { key = "7", mods = "Command", chars = "\u001b[14~\u0037" },
  { key = "8", mods = "Command", chars = "\u001b[14~\u0038" },
  { key = "9", mods = "Command", chars = "\u001b[14~\u0039" },
  # pane
  { key = "H", mods = "Command", chars = "\u001b[13~\u0068\u000d" },
  { key = "J", mods = "Command", chars = "\u001b[13~\u006a\u000d" },
  { key = "K", mods = "Command", chars = "\u001b[13~\u006b\u000d" },
  { key = "L", mods = "Command", chars = "\u001b[13~\u006c\u000d" },
  { key = "_", mods = "Command|Shift", chars = "\u001b[15~\u002d\u000d" },
  { key = "+", mods = "Command|Shift", chars = "\u001b[15~\u003d\u000d]" },
  { key = "/", mods = "Command", chars = "\u001b[13~\u0073\u000d" },
  { key = ";", mods = "Command", chars = "\u001b[13~\u0065" },
  { key = ":", mods = "Command|Shift", chars = "\u001b[13~\u0066" },
  { key = "H", mods = "Command|Shift", chars = "\u001b[17~\u0068\u000d" },
  { key = "J", mods = "Command|Shift", chars = "\u001b[17~\u006a\u000d" },
  { key = "K", mods = "Command|Shift", chars = "\u001b[17~\u006b\u000d" },
  { key = "L", mods = "Command|Shift", chars = "\u001b[17~\u006c\u000d" },
  # search
  { key = "F", mods = "Command", chars = "\u001b[20~" },
]

[scrolling]
history = 100000

[window]
decorations = "Buttonless"
opacity = 0.9
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"
blur = true

# macos
# [window.padding]
# x = 93

[shell]
program = "/opt/homebrew/bin/zellij"
