[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
# linux laptop
size = 10.5

# macos
# size = 17.5

[font.offset]
x = 0

# linux laptop
y = 0

# macos
# y = 4

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0001\u0008"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u000c"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u000a"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u000b"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0001"
key = "A"
mods = "Command"

[scrolling]
history = 100000

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"

# macos
# [window.padding]
# x = 10

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-As"]
