[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
# linux laptop
# size = 9.5

# macos
size = 16

[font.offset]
x = 0

# linux laptop
# y = 0

# macos
y = 5

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
key = "P"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "new-pane"]

[[keyboard.bindings]]
key = "H"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-focus", "left"]

[[keyboard.bindings]]
key = "L"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-focus", "right"]

[[keyboard.bindings]]
key = "J"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-focus", "down"]

[[keyboard.bindings]]
key = "K"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-focus", "up"]

[[keyboard.bindings]]
key = "T"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "new-tab"]

[[keyboard.bindings]]
key = "1"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "1"]

[[keyboard.bindings]]
key = "2"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "2"]

[[keyboard.bindings]]
key = "3"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "3"]

[[keyboard.bindings]]
key = "4"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "4"]

[[keyboard.bindings]]
key = "5"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "5"]

[[keyboard.bindings]]
key = "6"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "6"]

[[keyboard.bindings]]
key = "7"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "7"]

[[keyboard.bindings]]
key = "8"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "8"]

[[keyboard.bindings]]
key = "9"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "go-to-tab", "9"]

[[keyboard.bindings]]
key = "_"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "resize", "decrease"]

[[keyboard.bindings]]
key = "+"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "resize", "increase"]

[[keyboard.bindings]]
key = "F"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "switch-mode", "entersearch"]

[[keyboard.bindings]]
key = ";"
mods = "Command"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "toggle-pane-embed-or-floating", ""]

[[keyboard.bindings]]
key = ":"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "toggle-fullscreen", ""]

[[keyboard.bindings]]
key = "H"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-pane", "left"]

[[keyboard.bindings]]
key = "L"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-pane", "right"]

[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-pane", "up"]

[[keyboard.bindings]]
key = "J"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-pane", "down"]

[[keyboard.bindings]]
key = ">"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "move-pane"]

[[keyboard.bindings]]
key = "<"
mods = "Command|Shift"
  [keyboard.bindings.command]
  program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
  args = ["action", "next-swap-layout"]

# [[keyboard.bindings]]
# key = "G"
# mods = "Command"
#   [keyboard.bindings.command]
#   program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
#   args = ["run", "--", "/opt/homebrew/bin/lazygit"]

# [[keyboard.bindings]]
# key = "E"
# mods = "Command"
#   [keyboard.bindings.command]
#   program = "/Users/jimmy/dotfiles/.config/alacritty/exec-on-current-zellij.sh"
#   args = ["run", "--", "/usr/bin/env"]

[scrolling]
history = 100000

[window]
decorations = "Full"
opacity = 0.95
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"

# macos
# [window.padding]
# x = 93

[shell]
program = "/opt/homebrew/bin/zellij"
