# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[I](bold blue)"
error_symbol = "[I](bold red)"
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_one_symbol = "[❮❮❮](bold purple)"
vimcmd_replace_symbol = "[❮❮❮](bold purple)"
vimcmd_visual_symbol = "[V](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 50
show_milliseconds = true
format = "[$duration](bold yellow)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "🎄🎄🎄"

[conda]
symbol = "🐍 "
format = "via [$symbol$environment](bold green) "

[gcloud]
disabled = true
symbol = "️G"
format = '[$symbol(\($region\))]($style) '

[aws]
disabled = true
format = '[$symbol($profile )]($style)'
style = "orange"
symbol = "🅰 "

[kubernetes]
disabled = true
format = '[⛵ $cluster](dimmed green) '

[docker_context]
disabled = true

[nodejs]
disabled = true
