# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯❯❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗✗✗](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10
format = "[$duration](bold yellow)"

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "_"

[conda]
symbol = "🐍 "
format = "via [$symbol$environment](bold green) "

[gcloud]
disabled = true
symbol = "️G"
format = '[$symbol(\($region\))]($style) '

[aws]
disabled = true
format = '[$symbol($profile )]($style)'
style = "orange"
symbol = "🅰 "

[kubernetes]
disabled = true
format = '[⛵ $cluster](dimmed green) '

[docker_context]
disabled = true
